import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:archive/archive.dart';
import 'package:lexiora/modules/study_hub/domain/entities/study_task.dart';
import 'package:lexiora/modules/study_hub/domain/study_dates.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

enum ExportFormat {
  csv,
  pdf,
  xlsx;

  String get label => switch (this) {
        ExportFormat.csv => 'CSV',
        ExportFormat.pdf => 'PDF',
        ExportFormat.xlsx => 'Excel (.xlsx)',
      };
  String get ext => switch (this) {
        ExportFormat.csv => 'csv',
        ExportFormat.pdf => 'pdf',
        ExportFormat.xlsx => 'xlsx',
      };
  String get mime => switch (this) {
        ExportFormat.csv => 'text/csv',
        ExportFormat.pdf => 'application/pdf',
        ExportFormat.xlsx =>
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      };
}

/// Generates CSV / PDF / XLSX from study sessions and shares them via the OS
/// share sheet. Pure-Dart generation (pdf + archive); no server involved.
class StudyExportService {
  const StudyExportService();

  static const List<String> _headers = <String>[
    'Date', 'Type', 'Subject', 'Topic', 'Start', 'End', 'Priority', 'Status', 'Notes',
  ];

  List<List<String>> _matrix(List<StudyTask> tasks) => <List<String>>[
        _headers,
        for (final StudyTask t in tasks)
          <String>[
            t.day,
            t.isBreak ? 'Break' : 'Session',
            t.isBreak ? t.title : t.displaySubject,
            t.topic ?? '',
            formatMinuteOfDay(t.startMinute),
            formatMinuteOfDay(t.endMinute),
            t.priority.label,
            t.isBreak ? '' : t.status.label,
            t.notes ?? '',
          ],
      ];

  /// Builds [tasks] in [format] and opens the share sheet. Returns the filename.
  Future<String> exportAndShare({
    required String title,
    required List<StudyTask> tasks,
    required ExportFormat format,
  }) async {
    final List<List<String>> rows = _matrix(tasks);
    final List<int> bytes = switch (format) {
      ExportFormat.csv => utf8.encode(_csv(rows)),
      ExportFormat.pdf => await _pdf(title, rows),
      ExportFormat.xlsx => _xlsx(rows),
    };
    final String safe =
        title.replaceAll(RegExp(r'[^A-Za-z0-9_-]+'), '_').toLowerCase();
    final String filename = 'sapiora_$safe.${format.ext}';
    await shareBytes(bytes, filename, format.mime);
    return filename;
  }

  /// Writes [bytes] to a temp file and shares it (used for exports & backups).
  Future<void> shareBytes(List<int> bytes, String filename, String mime) async {
    final Directory dir = await getTemporaryDirectory();
    final File file = File('${dir.path}/$filename');
    await file.writeAsBytes(bytes, flush: true);
    await SharePlus.instance.share(
      ShareParams(
        files: <XFile>[XFile(file.path, mimeType: mime, name: filename)],
        subject: filename,
      ),
    );
  }

  // ── CSV ─────────────────────────────────────────────────────────────────────

  String _csv(List<List<String>> rows) =>
      rows.map((List<String> r) => r.map(_csvCell).join(',')).join('\r\n');

  String _csvCell(String v) {
    final bool needsQuote =
        v.contains(',') || v.contains('"') || v.contains('\n') || v.contains('\r');
    final String escaped = v.replaceAll('"', '""');
    return needsQuote ? '"$escaped"' : escaped;
  }

  // ── PDF ─────────────────────────────────────────────────────────────────────

  Future<Uint8List> _pdf(String title, List<List<String>> rows) async {
    final pw.Document doc = pw.Document();
    final List<String> headers = rows.first;
    final List<List<String>> data = rows.skip(1).toList();
    doc.addPage(
      pw.MultiPage(
        build: (pw.Context ctx) => <pw.Widget>[
          pw.Header(level: 0, text: title),
          pw.SizedBox(height: 8),
          if (data.isEmpty)
            pw.Text('No sessions in this range.')
          else
            pw.TableHelper.fromTextArray(
              headers: headers,
              data: data,
              headerStyle:
                  const pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
              cellStyle: const pw.TextStyle(fontSize: 8),
              cellAlignment: pw.Alignment.centerLeft,
              headerDecoration:
                  const pw.BoxDecoration(color: PdfColors.grey300),
            ),
          pw.SizedBox(height: 12),
          pw.Text('Generated by Sapiora Study Hub',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
        ],
      ),
    );
    return doc.save();
  }

  // ── XLSX (hand-built OOXML via archive; avoids a conflicting excel dep) ──────

  Uint8List _xlsx(List<List<String>> rows) {
    final StringBuffer sheet = StringBuffer()
      ..write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>')
      ..write('<worksheet xmlns="http://schemas.openxmlformats.org/'
          'spreadsheetml/2006/main"><sheetData>');
    for (int r = 0; r < rows.length; r++) {
      sheet.write('<row r="${r + 1}">');
      for (int c = 0; c < rows[r].length; c++) {
        sheet.write('<c r="${_colName(c)}${r + 1}" t="inlineStr">'
            '<is><t xml:space="preserve">${_xml(rows[r][c])}</t></is></c>');
      }
      sheet.write('</row>');
    }
    sheet.write('</sheetData></worksheet>');

    final Archive archive = Archive()
      ..addFile(ArchiveFile.string('[Content_Types].xml', _contentTypes))
      ..addFile(ArchiveFile.string('_rels/.rels', _rootRels))
      ..addFile(ArchiveFile.string('xl/workbook.xml', _workbook))
      ..addFile(ArchiveFile.string('xl/_rels/workbook.xml.rels', _workbookRels))
      ..addFile(ArchiveFile.string('xl/worksheets/sheet1.xml', sheet.toString()));
    return Uint8List.fromList(ZipEncoder().encode(archive));
  }

  static String _colName(int index) {
    String name = '';
    int n = index;
    while (true) {
      name = String.fromCharCode(65 + (n % 26)) + name;
      n = n ~/ 26 - 1;
      if (n < 0) break;
    }
    return name;
  }

  static String _xml(String s) => s
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;');

  static const String _contentTypes =
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
      '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
      '<Default Extension="xml" ContentType="application/xml"/>'
      '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
      '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
      '</Types>';

  static const String _rootRels =
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
      '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
      '</Relationships>';

  static const String _workbook =
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
      'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
      '<sheets><sheet name="Study Hub" sheetId="1" r:id="rId1"/></sheets></workbook>';

  static const String _workbookRels =
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
      '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
      '</Relationships>';
}
